# Generated by Django 3.2.4 on 2023-08-09 06:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_delete_authuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=30)),
                ('lead_image', models.ImageField(blank=True, null=True, upload_to='lead_images/')),
                ('designation', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('lead_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Converted', 'Converted')], max_length=20, null=True)),
                ('lead_score', models.CharField(blank=True, choices=[('25%', '25%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], max_length=10, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Lead',
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_source', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.alluser')),
            ],
            options={
                'db_table': 'LeadSource',
            },
        ),
        migrations.CreateModel(
            name='LeadNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leadnotes', to='lead.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.alluser')),
            ],
            options={
                'db_table': 'Leadnotes',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='leadsource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leadsource', to='lead.leadsource'),
        ),
        migrations.AddField(
            model_name='lead',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.alluser'),
        ),
    ]
