# Generated by Django 3.2.4 on 2023-07-03 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead_Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lead_Source_name', models.CharField(max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=30)),
                ('lead_image', models.ImageField(blank=True, null=True, upload_to='lead_images/')),
                ('designation', models.CharField(max_length=30)),
                ('phone_number', models.BigIntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('lead_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('converted', 'Converted')], max_length=20)),
                ('lead_score', models.CharField(choices=[('25%', '25%'), ('50%', '50%'), ('75%', '75%'), ('100%', '100%')], max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
                ('lead_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_source', to='lead.lead_source')),
            ],
        ),
    ]
