# Generated by Django 3.2.4 on 2023-08-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_alter_lead_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsource',
            name='lead_source',
            field=models.CharField(max_length=30),
        ),
    ]
