# Generated by Django 3.2.4 on 2023-09-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_alter_leadsource_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
