# Generated by Django 3.2.4 on 2023-10-19 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_lead_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='leadsource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leadsource', to='lead.leadsource'),
        ),
    ]
